package com.yonyou.nc.codevalidator.runtime;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.8
 * 2014-01-02T11:00:14.726+08:00
 * Generated source version: 2.7.8
 * 
 */
@WebServiceClient(name = "IRuleRuntimeExecutor", 
                  wsdlLocation = "http://localhost:9090/ruleexecute?wsdl",
                  targetNamespace = "http://runtime.codevalidator.nc.yonyou.com/") 
public class IRuleRuntimeExecutor extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://runtime.codevalidator.nc.yonyou.com/", "IRuleRuntimeExecutor");
    public final static QName IRuleRuntimeExecutorPort = new QName("http://runtime.codevalidator.nc.yonyou.com/", "IRuleRuntimeExecutorPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:9090/ruleexecute?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(IRuleRuntimeExecutor.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:9090/ruleexecute?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public IRuleRuntimeExecutor(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public IRuleRuntimeExecutor(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IRuleRuntimeExecutor() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public IRuleRuntimeExecutor(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public IRuleRuntimeExecutor(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public IRuleRuntimeExecutor(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns IRuleRuntimeExecutorPortType
     */
    @WebEndpoint(name = "IRuleRuntimeExecutorPort")
    public IRuleRuntimeExecutorPortType getIRuleRuntimeExecutorPort() {
        return super.getPort(IRuleRuntimeExecutorPort, IRuleRuntimeExecutorPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IRuleRuntimeExecutorPortType
     */
    @WebEndpoint(name = "IRuleRuntimeExecutorPort")
    public IRuleRuntimeExecutorPortType getIRuleRuntimeExecutorPort(WebServiceFeature... features) {
        return super.getPort(IRuleRuntimeExecutorPort, IRuleRuntimeExecutorPortType.class, features);
    }

}
