package com.yonyou.nc.codevalidator.runtime;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.8
 * 2014-01-02T11:00:14.679+08:00
 * Generated source version: 2.7.8
 * 
 */
@WebService(targetNamespace = "http://runtime.codevalidator.nc.yonyou.com/", name = "IRuleRuntimeExecutorPortType")
@XmlSeeAlso({ObjectFactory.class})
public interface IRuleRuntimeExecutorPortType {

    @RequestWrapper(localName = "execute", targetNamespace = "http://runtime.codevalidator.nc.yonyou.com/", className = "com.yonyou.nc.codevalidator.runtime.Execute")
    @WebMethod
    @ResponseWrapper(localName = "executeResponse", targetNamespace = "http://runtime.codevalidator.nc.yonyou.com/", className = "com.yonyou.nc.codevalidator.runtime.ExecuteResponse")
    public void execute(
            @WebParam(name = "arg0", targetNamespace = "http://runtime.codevalidator.nc.yonyou.com/")
            String arg0,
            @WebParam(name = "arg1", targetNamespace = "http://runtime.codevalidator.nc.yonyou.com/")
            String arg1,
            @WebParam(name = "arg2", targetNamespace = "http://runtime.codevalidator.nc.yonyou.com/")
            String arg2
    );
}
