
package com.yonyou.nc.codevalidator.runtime;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.8
 * 2014-01-02T11:00:14.492+08:00
 * Generated source version: 2.7.8
 * 
 */
public final class IRuleRuntimeExecutorPortType_IRuleRuntimeExecutorPort_Client {

    private static final QName SERVICE_NAME = new QName("http://runtime.codevalidator.nc.yonyou.com/", "IRuleRuntimeExecutor");

    private IRuleRuntimeExecutorPortType_IRuleRuntimeExecutorPort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = IRuleRuntimeExecutor.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        IRuleRuntimeExecutor ss = new IRuleRuntimeExecutor(wsdlURL, SERVICE_NAME);
        IRuleRuntimeExecutorPortType port = ss.getIRuleRuntimeExecutorPort();  
        
        {
        System.out.println("Invoking execute...");
        String _execute_arg0 = "";
        String _execute_arg1 = "";
        String _execute_arg2 = "";
        port.execute(_execute_arg0, _execute_arg1, _execute_arg2);


        }

        System.exit(0);
    }

}
